#jdbc:postgresql://ep-little-shape-ayzfut7l-pooler.c-5.us-east-2.aws.neon.tech/movies_database
#user=neondb_owner
 # &password=npg_8sbDQc5GVlNZ&sslmode=require&channelBinding=require
spring:
  datasource:
    url: jdbc:postgresql://ep-little-shape-ayzfut7l-pooler.c-5.us-east-2.aws.neon.tech/movies_database
    driverClassName: org.postgresql.Driver
    username: neondb_owner
    password: npg_8sbDQc5GVlNZ

  jpa:
    hibernate:
     ddl-auto:none