spring.application.name= firstapplication
spring.profiles.include = local
server.tomcat.threads.max=100
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100
server.tomcat.max-connections=100


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.connection.url=${spring.datasource.url}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.connection.isolation=TRANSACTION_READ_COMMITTED