name: Copy Docker Image from GitHub Container Registry to Amazon ECR

on:
    workflow_dispatch:
      inputs:
        aws-account-id:
          description: 'AWS Account ID'
          required: true
          type: string

        aws-region:
          description: 'AWS Region'
          required: true
          default: 'us-east-1'
          type: string

        aws-role-name:
          description: 'AWS IAM Role Name'
          required: true
          default: 'github-actions-ecr-role'
          type: string

permissions:
    id-token: write
    contents: read
    packages: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: test/firstapplication
  GHCR_IMAGE: ghcr.io/venuchalla/first-application:latest

jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
         - name: Login to GHCR
           uses: docker/login-action@v3
           with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

         - name: Pull image from GHCR
           run: |
               docker pull "$GHCR_IMAGE"     

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with:
            #aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY}}
            #aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_SECRET }}
            aws-region: ${{ inputs.aws-region }}
            role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.aws-role-name }}
         - name: Verify AWS login and branch
           run: |
            echo "======================================"
            echo "GitHub Branch: $GITHUB_REF_NAME"
            echo "GitHub Ref:    $GITHUB_REF"
            echo "======================================"
        
            if aws sts get-caller-identity; then
               echo "AWS LOGIN: SUCCESS"
            else
            echo "AWS LOGIN: FAILED"
            exit 1
            fi

         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v2

         - name: Tag image for ECR
           env:
             ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}

           run: |
             docker tag \
               "${{ inputs.ghcr-image }}" \
               "$ECR_REGISTRY/${{ inputs.ecr-repository }}:${GITHUB_SHA}"

         - name: Push image to ECR
           env:
             ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
           run: |
             docker push \
               "$ECR_REGISTRY/${{ inputs.ecr-repository }}:${GITHUB_SHA}"
             
             echo "Image successfully copied from GHCR to ECR"
             echo "ECR image: $ECR_REGISTRY/${{ inputs.ecr-repository }}:${GITHUB_SHA}"
